<h1>I. TÉRMINOS Y CONDICIONES</h1>
<p>

  Este documento describe los términos y condiciones generales (los "Términos y Condiciones Generales") y las políticas de privacidad (las "Políticas de Privacidad") aplicables al acceso y uso de los servicios ofrecidos por LINIO PERÚ S.A.C. ("los Servicios") dentro del sitio www.linio.com.pe, sus subdominios y/u otros dominios (urls) relacionados (en adelante "linio.com" o el "Sitio"), en donde éstos Términos y Condiciones se encuentren. Cualquier persona que desee acceder y/o suscribirse y/o usar el Sitio o los Servicios podrá hacerlo sujetándose a los Términos y Condiciones Generales y las Políticas de Privacidad, junto con todas las demás políticas y principios que rigen linio.com.pe y que son incorporados al presente directamente o por referencia o que son explicados y/o detallados en otras secciones del Sitio. En consecuencia, todas las visitas y todos los contratos y transacciones que se realicen en este Sitio, así como sus efectos jurídicos, quedarán regidos por estas reglas y sometidos a la legislación aplicable en Perú.

  Los Términos y Condiciones y las Políticas de Privacidad contenidos en este instrumento se aplicarán y se entenderán como parte integral de todos los actos y contratos que se ejecuten o celebren mediante los sistemas de oferta y comercialización comprendidos en este sitio entre los usuarios de este sitio y LINIO PERÚ S.A.C. (en adelante "LINIO PERÚ S.A.C.", "LINIO" o "la Empresa", indistintamente), y por cualquiera de las otras sociedades o empresas que sean filiales o vinculadas a ella, y que hagan uso de este sitio, a las cuales se las denominará en adelante también en forma indistinta como las "Empresas", o bien la "Empresa Oferente", el "Proveedor" o la "Empresa Proveedora", según convenga al sentido del texto.

  En caso que las Empresas hubieran fijado sus propios Términos y Condiciones y sus Políticas de Privacidad para los actos y contratos que realicen en este sitio, ellas aparecerán en esta página señalada con un link o indicada como parte de la promoción de sus ofertas y promociones y prevalecerán sobre éstas. CUALQUIER PERSONA QUE NO ACEPTE ESTOS TÉRMINOS Y CONDICIONES GENERALES Y LAS POLÍTICAS DE PRIVACIDAD, LOS CUALES TIENEN UN CARÁCTER OBLIGATORIO Y VINCULANTE, DEBERÁ ABSTENERSE DE UTILIZAR EL SITIO Y/O LOS SERVICIOS.

  El Usuario debe leer, entender y aceptar todas las condiciones establecidas en los Términos y Condiciones Generales y en las Políticas de Privacidad de LINIO PERÚ S.A.C. así como en los demás documentos incorporados a los mismos por referencia, previo a su registro como Usuario de linio.com.pe y/o a la adquisición de productos y/o entrega de cualquier dato, quedando sujetos a lo señalado y dispuesto en los Términos y Condiciones.

  Cuando usted visita Linio.com.pe se está comunicando con LINIO de manera electrónica. En ese sentido, usted brinda su consentimiento para recibir comunicaciones de LINIO por correo electrónico o mediante la publicación de avisos en su portal.
</p>
